
- name: Установка jq без сбора фактов
  hosts: remote
  gather_facts: no

  tasks:
    - name: install jq
      ansible.builtin.apt:
        name: jq
        state: present
        update_cache: yes
      become: yes

    - name: remove jq
      ansible.builtin.apt:
        name: jq
        state: absent
      become: yes
