- name: Установка Nginx и обновление конфигурации
  hosts: remote
  vars:
    root_dir: /etc/nginx
    nginx_port: 80

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes
      tags: nginx

    - name: copy index.html
      ansible.builtin.template:
        src: files/index.html.j2
        dest: /usr/share/nginx/html/index.html
      become: yes
      tags: nginx

    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: "{{ root_dir }}/nginx.conf"
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
